StatzyGUI-main/statzy/routes/login.py
from flask import Blueprint, request, session, redirect, url_for, render_template
from helper import get_db

bp_login = Blueprint('login', __name__)


@bp_login.route('/')
def index():
    title = 'Statzy'
    return render_template('login.html', title=title)

@bp_login.route('/login', methods=['POST'])
def login():
    print("Entering login function")
    session['username'] = request.form['username']
    session['password'] = request.form['password']
    print(f"Username: {session['username']}, Password: {session['password']}")
    try:
        get_db()
        print("Database connection successful")
        return redirect(url_for('home.start'))
    except Exception as e:
        print(f"Database connection failed: {e}")
        return 'Database connection failed! Login'

StatzyGUI-main/statzy/routes/person.py
from flask import Blueprint, render_template, request, redirect, url_for
from helper import get_cursor, get_db, db_execute


bp_person = Blueprint('person', __name__)


@bp_person.route('/person')
def person():
    return render_template('person.html')


@bp_person.route('/personSuche')
def personSuche():
    return render_template('personSuche.html', warning=0)


@bp_person.route('/personAnsehen', methods=['GET', 'POST'])
def personAnsehen():
    if request.method == 'POST':
        name = request.form['name']
        try:
            cursor = get_cursor()
            query = "SELECT name, telefonnummer, dez, vornam, person_id, zeitpunkt_ins, user_ins, zeitpunkt_upd, user_upd FROM person WHERE name ~* '" + name + "' ORDER BY name "
            cursor.execute(query)
            results = cursor.fetchall()

            if not results:
                return render_template('person.html', warning=1, name=name)

            name, telefonnummer, dez, vornam, person_id, zeitpunkt_ins, user_ins, zeitpunkt_upd, user_upd = results[
                0]

            return render_template('personAnsehen.html', name=name, telefonnummer=telefonnummer, dez=dez, vornam=vornam, person_id=person_id, zeitpunkt_ins=zeitpunkt_ins, user_ins=user_ins, zeitpunkt_upd=zeitpunkt_upd, user_upd=user_upd)
        except Exception as e:
            return 'Fehler', e
    else:
        # ? falls eine id übergeben wird nach id suchen
        if request.args.get('id'):
            id = request.args.get('id')
            try:
                cursor = get_cursor()
                query = "SELECT name, telefonnummer, dez, vornam, person_id, zeitpunkt_ins, user_ins, zeitpunkt_upd, user_upd FROM person WHERE person_id = '" + id + "' ORDER BY name"
                cursor.execute(query, (id,))
                results = cursor.fetchall()
                if not results:
                    return render_template('person.html', warning=1, name=name)
                name, telefonnummer, dez, vornam, person_id, zeitpunkt_ins, user_ins, zeitpunkt_upd, user_upd = results[
                    0]
                return render_template('personAnsehen.html', name=name, telefonnummer=telefonnummer, dez=dez, vornam=vornam, person_id=person_id, zeitpunkt_ins=zeitpunkt_ins, user_ins=user_ins, zeitpunkt_upd=zeitpunkt_upd, user_upd=user_upd)
            except Exception as e:
                return 'Fehler', e
        else:
            name = request.args.get('name')
            try:
                cursor = get_cursor()
                query = "SELECT name, telefonnummer, dez, vornam, person_id, zeitpunkt_ins, user_ins, zeitpunkt_upd, user_upd FROM person WHERE name ~* '" + name + "' ORDER BY name"
                cursor.execute(query, (name,))
                results = cursor.fetchall()
                if not results:
                    return render_template('person.html', warning=1, name=name)
                name, telefonnummer, dez, vornam, person_id, zeitpunkt_ins, user_ins, zeitpunkt_upd, user_upd = results[
                    0]
                return render_template('personAnsehen.html', name=name, telefonnummer=telefonnummer, dez=dez, vornam=vornam, person_id=person_id, zeitpunkt_ins=zeitpunkt_ins, user_ins=user_ins, zeitpunkt_upd=zeitpunkt_upd, user_upd=user_upd)
            except Exception as e:
                return 'Fehler', e


@bp_person.route('/personEditieren', methods=['POST'])
def personEditieren():
    print("Test 1")
    # nameOld = request.form['name']
    # print(nameOld)
    name = request.form['name']
    print(name)
    try:
        cursor = get_cursor()
        query = "SELECT name, telefonnummer, dez, vornam, person_id, zeitpunkt_ins, user_ins, zeitpunkt_upd, user_upd FROM person WHERE name ~* '" + name + "' ORDER BY name"
        cursor.execute(query)
        results = cursor.fetchall()
        name, telefonnummer, dez, vornam, person_id, zeitpunkt_ins, user_ins, zeitpunkt_upd, user_upd = results[
            0]
        return render_template('personEditieren.html', name=name, telefonnummer=telefonnummer, dez=dez, vornam=vornam, person_id=person_id, zeitpunkt_ins=zeitpunkt_ins, user_ins=user_ins, zeitpunkt_upd=zeitpunkt_upd, user_upd=user_upd)
    except:
        return 'Fehler'


@bp_person.route('/personUpdate', methods=['POST'])
def personUpdate():
    name = request.form['name']
    telefonnummer = request.form['telefonnummer']
    dez = request.form['dez']
    vornam = request.form['vornam']
    person_id = request.form['person_id']
    # zeitpunkt_ins = request.form['zeitpunkt_ins']
    # user_ins = request.form['user_ins']
    # zeitpunkt_upd = request.form['zeitpunkt_upd']
    # user_upd = request.form['user_upd']
    # zeitpunkt_ins=NULL, user_ins=NULL, zeitpunkt_upd=NULL, user_upd=NULL
    try:
        cursor = get_cursor()
        query = "UPDATE person SET name=%s, telefonnummer=%s, dez=%s, vornam=%s WHERE person_id=%s"
        # print(query, (name, telefonnummer, dez, vornam, name))
        cursor.execute(query, (name, telefonnummer, dez, vornam, person_id))
        get_db().commit()
        return redirect(url_for('person.personAnsehen', name=name))
    except Exception as e:
        return 'Fehler: ' + str(e)


@bp_person.route('/personValidate', methods=['POST'])
def personValidate():
    return render_template('personErstellen.html')


@bp_person.route('/personErstellen', methods=['POST'])
def personErstellen():
    name = request.form['name']
    telefonnummer = request.form['telefonnummer']
    dez = request.form['dez']
    vornam = request.form['vornam']
    print("test 0")
    try:
        cursor = get_cursor()
        print('test 1')
        query = "INSERT INTO person (name, telefonnummer, dez, vornam) VALUES ('" + name + "', '" + \
            telefonnummer + "', '" + dez + "', '" + vornam + "')"
        print("test 2")
        cursor.execute(query)
        print("test 3")
        cursor.connection.commit()
        print("test 4")
        cursor.close()
        # debug print(query rückgabe)
        print('Person wurde erstellt')
        return render_template('personAnsehen.html', name=name, telefonnummer=telefonnummer, dez=dez, vornam=vornam)
    except Exception as e:
        return 'Fehler: ' + str(e)


@bp_person.route('/persServRelAnsehen')
def persServRelAnsehen():
    try:
        results = db_execute("SELECT * FROM person")
        return render_template('persServRelAnsehen.html', data=results)
    except Exception as e:
        results = []
        return f"Database query failed! {e}"

StatzyGUI-main/statzy/routes/query.py
from flask import Blueprint, render_template, request
from helper import get_cursor
import json


bp_query = Blueprint('query', __name__)
    
    
@bp_query.route('/query', methods=['POST'])
def query():
    table_name = request.form['table']
    try:
        cursor = get_cursor()
        cursor.execute(f"SELECT * FROM {table_name}")
        results = cursor.fetchall()
        return render_template('query.html', table_name=table_name, data=results, cursor=cursor)
    except Exception as e:
        results = []
        return f"Database query failed! {e}"
    
    
@bp_query.route('/getnames', methods=['GET'])
def getnames():
    input = request.args.get('input')
    cursor = get_cursor()
    cursor.execute("SELECT person_id, vornam, name, dez FROM person WHERE name ILIKE %s OR vornam ILIKE %s OR dez ILIKE %s", (f"%{input}%", f"%{input}%", f"%{input}%",))
    results = cursor.fetchall()
    names = [{"person_id": result[0], "vornam": result[1], "name": result[2], "dez": result[3]} for result in results]
    print(json.dumps(names))
    return json.dumps(names)

StatzyGUI-main/statzy/templates/datenbanken.html
{% extends "layout.html" %} {% block content %}
<div class="container mx-auto">
  <div class="flex flex-col items-center justify-center py-20">
    <h1 class="mb-4 text-2xl font-medium">Datenbanken</h1>
    <form action="{{ url_for('query.query') }}" method="POST">
      <div class="relative inline-block">
        <select
          class="block w-full px-4 py-2 pr-8 leading-tight bg-white border border-gray-400 rounded shadow appearance-none hover:border-gray-500 focus:outline-none focus:shadow-outline"
          name="table">
          {% for table in tables %}
          <option value="{{ table }}">{{ table }}</option>
          {% endfor %}
        </select>
        <div class="absolute inset-y-0 right-0 flex items-center px-2 text-gray-700 pointer-events-none">
          <svg class="w-4 h-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path d="M0 0h20v20H0z" fill="none" />
            <path d="M7 9l3 3 3-3H7z" />
          </svg>
        </div>
      </div>
      <button
        class="px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700 focus:outline-none focus:shadow-outline"
        type="submit">
        Submit
      </button>
    </form>
  </div>
</div>
{% endblock %}

StatzyGUI-main/statzy/templates/fachverfahrenEditieren.html
{% extends "layout.html" %}
{% block content %}
<div class="font-sans text-gray-900 bg-gray-100">
  <div class="py-6 mx-auto max-w-7xl sm:px-6 lg:px-8">
    <div class="px-4 py-6 sm:px-0">
      <h1 class="mb-8 text-3xl font-bold text-center">
        Fachverfahren Editieren
      </h1>
      <form action="{{ url_for('fachverfahren.fachverfahrenUpdate') }}" method="POST" class="max-w-3xl mx-auto">
        <script>
          var suggestionsMap = {};

          function showSuggestions(input, fieldId) {
            if (input.length == 0) {
              document.getElementById(fieldId + "-list").innerHTML = "";
              return;
            }
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function () {
              if (this.readyState == 4 && this.status == 200) {
                var names = JSON.parse(this.responseText);
                var suggestions = "";
                for (var i = 0; i < names.length; i++) {
                  suggestions += "<option value='" + names[i].name + "' data-vorname='" + names[i].vornam + "' data-nachname='" + names[i].name + "' data-dez='" + names[i].dez + "' data-person-id='" + names[i].person_id + "'>" + names[i].person_id + " " + names[i].vornam + " " + names[i].name + " (" + names[i].dez + ") </option>";
                  // Update the suggestionsMap
                  suggestionsMap[names[i].name] = names[i].person_id + " " + names[i].vornam + " " + names[i].name + " (" + names[i].dez + ")";
                }
                document.getElementById(fieldId + "-list").innerHTML = suggestions;
              }
            };
            xmlhttp.open("GET", "/getnames?input=" + input, true);
            xmlhttp.send();
          }

          function setPersonId(input, fieldId) {
            var options = document.getElementById(fieldId + '-list').options;
            for (var i = 0; i < options.length; i++) {
              if (options[i].value == input.value) {
                var personId = options[i].getAttribute('data-person-id');
                document.getElementById(fieldId + '-id').value = personId;
                // Set input field to match suggestion format
                input.value = suggestionsMap[input.value];
                break;
              }
            }
          }

        </script>

        <hr class="my-8 border-gray-300" />

        <div class="max-w-3xl mx-auto">
          <div class="px-8 pt-6 pb-8 mb-4 bg-white rounded shadow-md">
            <div class="mb-6">
              <label class="block mb-2 font-bold" for="verfahrens-tag">
                Verf.-Tag:
              </label>
              <input
                class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                type="text" id="verfahrens-tag" name="tag" value="{{ tag }}">
            </div>

            <div class="mb-6">
              <label class="block mb-2 font-bold" for="it-verfahren-namen">
                Namen des IT Verfahrens:
              </label>
              <input
                class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                type="text" id="it-verfahren-namen" name="it-verfahren-namen" value="{{ name}}" />
            </div>
            <div class="mb-6">
              <label class="block mb-2 font-bold" for="verfahrens-id">
                Verfahrens-ID:
              </label>
              <input
                class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                type="text" id="verfahrens-id" name="verfahrens-id" value="{{ verf_id }}" />
            </div>

            <div class="mb-6">
              <label class="block mb-2 font-bold" for="verwendungszweck">
                Verwendungszweck:
              </label>
              <input
                class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                type="text" id="verwendungszweck" name="verwendungszweck" value="{{ vewendungszweck }}">
            </div>
            <div class="mb-6">
              <label class="block mb-2 font-bold" for="laufzeit">
                Laufzeit:
              </label>
              <input
                class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                type="text" id="laufzeit" name="laufzeit" value="{{ laufzeitverfahren }}">
            </div>

            <div class="mb-6">
              <label class="block mb-2 font-bold" for="auftraggeber">Auftraggeber:</label>
              <input
                class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                type="text" id="auftraggeber" name="auftraggeber" value="{{ auftraggeber }}"
                oninput="showSuggestions(this.value, 'auftraggeber'); setPersonId(this, 'auftraggeber');"
                autocomplete="off" list="auftraggeber-list">
              <datalist id="auftraggeber-list" class="mt-1 bg-white rounded-md shadow-lg suggestions-list"></datalist>
              <input type="hidden" id="auftraggeber-id" name="auftraggeber-id">
            </div>

            <div class="mb-6">
              <label class="block mb-2 font-bold" for="verf_bet">Verfahrens Betreuung:</label>
              <input
                class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                type="text" id="verf_bet" name="verf_bet" value="{{ verf_betreuung }}"
                oninput="showSuggestions(this.value, 'verf_bet'); setPersonId(this, 'verf_bet');" autocomplete="off"
                list="verf_bet-list">
              <datalist id="verf_bet-list" class="mt-1 bg-white rounded-md shadow-lg suggestions-list"></datalist>
              <input type="hidden" id="verf_bet-id" name="verf_bet-id">
            </div>

            <div class="mb-6">
              <label class="block mb-2 font-bold" for="kundenmanagement">Kundenmanagement:</label>
              <input
                class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                type="text" id="kundenmanagement" name="kundenmanagement" value="{{ kundenmanagement }}"
                oninput="showSuggestions(this.value, 'kundenmanagement'); setPersonId(this, 'kundenmanagement');"
                autocomplete="off" list="kundenmanagement-list">
              <datalist id="kundenmanagement-list"
                class="mt-1 bg-white rounded-md shadow-lg suggestions-list"></datalist>
              <input type="hidden" id="kundenmanagement-id" name="kundenmanagement-id">
            </div>

            <div class="mb-6">
              <label class="block mb-2 font-bold" for="fachadmin">Fachadministration:</label>
              <input
                class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                type="text" id="fachadmin" name="fachadmin" value="{{ fachadministration }}"
                oninput="showSuggestions(this.value, 'fachadmin'); setPersonId(this, 'fachadmin');" autocomplete="off"
                list="fachadmin-list">
              <datalist id="fachadmin-list" class="mt-1 bg-white rounded-md shadow-lg suggestions-list"></datalist>
              <input type="hidden" id="fachadmin-id" name="fachadmin-id">
            </div>


            <hr class="my-8 border-gray-300" />

            <div class="flex items-center justify-center">
              <button
                class="px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700 focus:outline-none focus:shadow-outline"
                type="submit">Ändern</button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

StatzyGUI-main/statzy/templates/login.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='/build/theme.css') }}" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='/css/theme.css') }}" />
  <title>{{ title }}</title>
</head>

<body>
  <div class="bg-gray-100">
    <div class="flex items-center justify-center min-h-screen">
      <div class="w-full max-w-md px-6 py-8 bg-white rounded-lg shadow-md">
        <h1 class="mb-4 text-2xl font-medium">Login to Statzy</h1>
        <form action="{{ url_for('login.login') }}" method="POST">
          <div class="mb-4">
            <label class="block mb-2 font-bold text-gray-700" for="username">
              Username
            </label>
            <input class="w-full px-3 py-2 border rounded-lg" type="text" name="username" id="username" />
          </div>
          <div class="mb-4">
            <label class="block mb-2 font-bold text-gray-700" for="password">
              Password
            </label>
            <input class="w-full px-3 py-2 border rounded-lg" type="password" name="password" id="password" />
          </div>
          <div class="flex items-center justify-between">
            <button
              class="px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700 focus:outline-none focus:shadow-outline"
              type="submit">
              Login
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</body>

</html>

StatzyGUI-main/statzy/templates/person.html
{% extends "layout.html" %}

{% block content %}
<div class="font-sans text-gray-900 bg-gray-100">
    <div class="py-6 mx-auto max-w-7xl sm:px-6 lg:px-8">
        <div class="px-4 py-6 sm:px-0">
            <h1 class="mb-8 text-3xl font-bold text-center">
                Person Suchen
            </h1>

            <hr class="my-8 border-gray-300" />

            <form action="{{ url_for('person.personAnsehen') }}" method="POST" class="max-w-3xl mx-auto">
                <div class="flex flex-wrap">
                    <div class="w-full">
                        <label class="block mb-2 font-bold" for="name">
                            Person Name:
                        </label>
                    </div>
                    <div class="w-4/6 md:w-5/6">
                        <input
                            class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                            type="text" id="name" name="name" value="{{ name }}">
                    </div>

                    <div class="w-2/6 pl-4 md:w-1/6">
                        <button
                            class="px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700 focus:outline-none focus:shadow-outline"
                            type="submit">
                            Suchen
                        </button>
                    </div>
            </form>

            {% if warning == 1 %}
            <div class="max-w-md mx-auto mt-8">
                <div class="px-8 pt-6 pb-8 mb-4 bg-white rounded shadow-md">
                    <p class="mb-4 font-bold text-center text-red-500">Diese Person gibt es nicht!</p>
                    <form action="{{ url_for('person.personValidate') }}" method="POST"
                        class="flex items-center justify-center">
                        <input class="hidden" type="text" id="name" name="name" value="{{ name }}">
                        <input class="hidden" type="text" id="telefonnummer" name="telefonnummer"
                            value="{{ telefonnummer }}">
                        <input class="hidden" type="text" id="vornam" name="vornam" value="{{ vornam }}">
                        <input class="hidden" type="text" id="dez" name="dez" value="{{ dez }}">
                        <button
                            class="px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700 focus:outline-none focus:shadow-outline"
                            type="submit">
                            Erstellen
                        </button>
                    </form>
                </div>
            </div>

            {% endif %}

        </div>
    </div>
</div>









<!--    Tabllenstruktur für Übericht
    <div class="flex justify-center">
        <table class="mx-10 border border-collapse shadow-xl table-auto border-slate-400">
            <thead class="border-gray-300 border-1">
                <tr class="bg-blue-300 ">
                <th class="px-6 py-3"> Name </th>
                <th class="px-6 py-3"> Vorname </th>
                <th class="px-6 py-3"> Dezernat </th>
                <th class="px-6 py-3"> Telefonnummer </th>
                <th class="px-6 py-3"> Erstellt am</th>
                <th class="px-6 py-3"> Erstellt von </th>
                <th class="px-6 py-3"> Letzte Änderung am </th>
                <th class="px-6 py-3"> Letzte Änderung von </th>   
                </tr>
            </thead>
            <tbody class="text-center bg-white border-2 border-gray-300 divide-y divide-gray-200">
                <tr class="duration-300 hover:bg-blue-500 hover:text-white hover:scale-105">
                    <td> Name</td>
                    <td> Vorname</td>
                    <td> Dezernat</td>
                    <td> Telefonnummer</td>
                    <td> Erstellt am</td>
                    <td> Erstellt von</td>
                    <td> Letzte Änderung am</td>
                    <td> Letzte Änderung von</td>
                </tr>
            </tbody>
        </table>
    </div>
-->


{% endblock content %}

StatzyGUI-main/statzy/templates/personEditieren.html
{% extends "layout.html" %} {% block content %}
<div class="font-sans text-gray-900 bg-gray-100">
    <div class="py-6 mx-auto max-w-7xl sm:px-6 lg:px-8">
        <div class="px-4 py-6 sm:px-0">
            <h1 class="mb-8 text-3xl font-bold text-center">
                Person Erstellen
            </h1>
            <hr class="my-8 border-gray-300" />
        </div>
        <!--! form start-->
        <form action="{{ url_for('person.personErstellen') }}" method="POST" class="max-w-3xl mx-auto">
            <div class="mb-6">
                <label class="block mb-2 font-bold" for="name">
                    Name:
                </label>
                <input
                    class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                    type="text" id="name" name="name" value="{{ name }}">
            </div>
            <div class="mb-6">
                <label class="block mb-2 font-bold" for="telefonnummer">
                    Telefonnummer:
                </label>
                <input
                    class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                    type="text" id="telefonnummer" name="telefonnummer" value="{{ telefonnummer }}" />
            </div>
            <div class="mb-6">
                <label class="block mb-2 font-bold" for="dez">
                    Dezernat:
                </label>
                <input
                    class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                    type="text" id="dez" name="dez" value="{{ dez }}" />
            </div>
            <div class="mb-6">
                <label class="block mb-2 font-bold" for="vornam">
                    Vorname:
                </label>
                <input
                    class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                    type="text" id="vornam" name="vornam" value="{{ vornam }}">
            </div>

            <div class="mb-6 ">
                <label class="block mb-2 font-bold " for=" zeitpunkt_ins">
                    Erstellt am:
                </label>
                <input
                    class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                    type="text" id="zeitpunkt_ins" name="zeitpunkt_ins" value="{{
                zeitpunkt_ins
                }}" readonly disabled>
            </div>
            <div class="mb-6 ">
                <label class="block mb-2 font-bold " for=" user_ins"> Erstellt von: </label>
                <input
                    class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                    type="text" id="user_ins" name="user_ins" value="{{
                user_ins
                }}" readonly disabled>
            </div>
            <div class="mb-6 ">
                <label class="block mb-2 font-bold " for=" zeitpunkt_upd"> Letzte Änderung am: </label>
                <input
                    class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                    type="text" id="zeitpunkt_upd" name="zeitpunkt_upd" value="{{
                zeitpunkt_upd
                }}" readonly disabled>
            </div>
            <div class="mb-6 ">
                <label class="block mb-2 font-bold " for=" user_upd"> Letzte Änderung von: </label>
                <input
                    class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                    type="text" id="user_upd" name="user_upd" value="{{
                user_upd
                }}" readonly disabled>
            </div>
            <hr class="my-8 border-gray-300 " />
            <div class="flex items-center justify-center ">
                <button
                    class="px-4 py-2 font-bold text-white bg-blue-500 rounded  hover:bg-blue-700 focus:outline-none focus:shadow-outline"
                    type="submit">
                    Ändern
                </button>
            </div>
            <input class="hidden" id="person_id" name="person_id" value="{{ person_id }}">
        </form>
        <!--! form end-->
    </div>
</div>
{% endblock %}

StatzyGUI-main/statzy/templates/personErstellen.html
{% extends "layout.html" %}
{% block content %}
<div class="font-sans text-gray-900 bg-gray-100">
    <div class="py-6 mx-auto max-w-7xl sm:px-6 lg:px-8">
        <div class="px-4 py-6 sm:px-0">
            <h1 class="mb-8 text-3xl font-bold text-center">
                Person Erstellen
            </h1>
            <hr class="my-8 border-gray-300" />
        </div>
        <!--! form start-->
        <form action="{{ url_for('person.personErstellen') }}" method="POST" class="max-w-3xl mx-auto">
            <div class="mb-6">
                <label class="block mb-2 font-bold" for="name">
                    Name:
                </label>
                <input
                    class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                    type="text" id="name" name="name" value="{{ name }}">
            </div>
            <div class="mb-6">
                <label class="block mb-2 font-bold" for="telefonnummer">
                    Telefonnummer:
                </label>
                <input
                    class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                    type="text" id="telefonnummer" name="telefonnummer" value="{{ telefonnummer }}" />
            </div>
            <div class="mb-6">
                <label class="block mb-2 font-bold" for="dez">
                    Dezernat:
                </label>
                <input
                    class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                    type="text" id="dez" name="dez" value="{{ dez }}" />
            </div>
            <div class="mb-6">
                <label class="block mb-2 font-bold" for="vornam">
                    Vorname:
                </label>
                <input
                    class="w-full px-3 py-2 leading-tight text-gray-900 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                    type="text" id="vornam" name="vornam" value="{{ vornam }}">
            </div>
            <hr class="my-8 border-gray-300 " />
            <div class="flex items-center justify-center ">
                <button
                    class="px-4 py-2 font-bold text-white bg-blue-500 rounded  hover:bg-blue-700 focus:outline-none focus:shadow-outline"
                    type="submit">
                    Erstellen
                </button>
            </div>
            <input class="hidden" id="name" name="name" value="{{ name }}">
        </form>
        <!--! form end-->
    </div>
</div>
{% endblock content %}